### ISSUE TITLE
Battery SOH: Too many digits for Y-axis on sensor detail page

### ISSUE THREAD

**Issue by PV-Joe** [davidrapan/ha-solarman#109]
Just a small bug and probably easy to fix 😄

**Screenshots**
![image](https://github.com/user-attachments/assets/006a0714-a606-4574-afaa-4c10c0649305)

**Metadata:**
Version: v24.08.21

**Comment by davidrapan** [comment]
That is python itself related and you can read more 'bout it here: https://docs.python.org/3/tutorial/floatingpoint.html

**Comment by PV-Joe** [comment]
Oh well, never mind and thanks for explaining.
It has to remain ugly then 😂

**Comment by frsantos** [comment]
Can it be rounded to 2 digits on read?

**Comment by davidrapan** [comment]
Did you read the article? 😆 It is rounded, the precision error is not made during saving the value but by reading by HA from db. 😆

**Comment by frsantos** [comment]
Ok, so round on presentation? I think you can set a display presentation on HA, but not sure if it affects here.

**Comment by davidrapan** [comment]
> but not sure if it affects here.

It does not affects graph, just showed value.

**Comment by frsantos** [comment]
> It does not affects graph, just showed value.

A pity

**Comment by davidrapan** [comment]
IF solution exists it has to be implemented on the HA's side. Integration has no control over this particular thing.
