### ISSUE TITLE
Using of own yaml - fail

### ISSUE THREAD

**Issue by amiko24** [davidrapan/ha-solarman#11]
Hi David,
I have created my own yaml file and added it to the folder "inverter_definitions". I can't select my yaml fail in the configuration because the name is not displayed. At StephanJoubert all inverter yaml are listed in the fail const.py.  
In which file can I find the list of inverter yaml files?

**Comment by amiko24** [comment]
![Const](https://github.com/davidrapan/ha-solarman/assets/125893667/279a63fb-c759-4dd0-a0c2-b10b1affda80)

**Comment by PV-Joe** [comment]
I have tried to load an individual configuration without success. The file just doesn’t show up in the configuration selector.

I duplicated an existing file and renamed it for backup purposes and overwrote the original file with my custom configuration.

Maybe it helps as a workaround until we know more?

**Comment by amiko24** [comment]
Good idea, thank you.

**Comment by davidrapan** [comment]
Hi guys, from the screenshot provided it's obvious you are not using latest version. Please kindly update the latest code and try again.

Have fun!
