### ISSUE TITLE
Device Setup failed with release higher than v24.08.17 - "Device Time" parsing error

### ISSUE THREAD

**Issue by optim1se** [davidrapan/ha-solarman#128]
**Describe the bug:**
After Upgrade from Solarman v24.08.17 to v24.08.21, my Device(DEYE SUN-M80G3-EU-Q0) in Solarman shows: "Setup failed, retrying: [<inverter_serialnumber>] Querying <inverter_ip-adress> failed."

After downgrade to v24.08.17, Inverter is reachable again and Solarman is working as expected.

**Attach the debug log:**
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.solarman.parser
Quelle: custom_components/solarman/parser.py:179
Integration: Solarman (Dokumentation, Probleme)
Erstmals aufgetreten: 10:30:29 (120 Vorkommnisse)
Zuletzt protokolliert: 10:57:22

ParameterParser.try_parse: start: 0, length: 113, [..., 12288, 0, 0, ....], definition: {'name': 'Device Time', 'class': '', 'state_class': '', 'uom': '', 'scale': 1, 'rule': 8, 'registers': [22, 23, 24], 'icon': 'mdi:clock-time-three-outline'} [ValueError: time data '48/0/0 0:0:0' does not match format '%y/%m/%d %H:%M:%S']
```

**To Reproduce:**
1. Update Solarman over HACS to v24.08.21
2. Restart Homeassistant

**Expected behavior:**
Inverter should be reachable after update to v24.08.21.

**Metadata:**
Template type: deye_2mppt
Inverter type: DEYE SUN-M80G3-EU-Q0
Version: v24.08.21

**Additional context**
Inverter has no internet access. That may be the reason for the strange time.

**Comment by davidrapan** [comment]
[fix: Ignore incorrect datetime while parsing](https://github.com/davidrapan/ha-solarman/commit/60bd1e002f241780f28e6d71bacff5150da3b3d2)

_Will be part of today's pre-release._

And could you maybe check why that happened? If it's due to reading incorrect registers or maybe cause of incorrect time in the inverter?

Thanks. 😉

**Comment by CrazyUs3r** [comment]
I have g3

**Comment by davidrapan** [comment]
Ah I see, okay then. Missing time won't be a problem anymore. 👍
