### ISSUE TITLE
Wrong integration overview documentation and issues links

### ISSUE THREAD

**Issue by Kedryn** [davidrapan/ha-solarman#13]
![image](https://github.com/davidrapan/ha-solarman/assets/12759632/d728eb5e-6087-4553-8d09-2e7c4c6e172f)
those links points to 404 because the url contains ha_solarman instead of ha-solarman

https://github.com/davidrapan/ha_solarman/

**Comment by davidrapan** [comment]
Hi, thank you for pointing it out! I'll make sure to fix that!

Thanks again and have fun!

**Comment by davidrapan** [comment]
Fixed in [e5bced4](https://github.com/davidrapan/ha-solarman/commit/e5bced4a82cbbe393b197d46a36c331a7b916f6a)
