### ISSUE TITLE
Deye Inverter connects but not getting any valid values

### ISSUE THREAD

**Issue by Milliamper** [davidrapan/ha-solarman#148]
The integration finds my Deye Hybrid Inverter (SUN-5K-SG04LP3-EU) on the network but it cannot read any valid values.
<img width="753" alt="deye_error" src="https://github.com/user-attachments/assets/d9f85502-63ff-41d0-b1cf-08c61c35fa4a">
I have also tried using different yaml config files (deye_string.yaml and deye_hybrid.yaml) but none of them helped.
I also attached the log file output.
[home-assistant_solarman_2024-09-11T19-22-33.924Z.log](https://github.com/user-attachments/files/16969236/home-assistant_solarman_2024-09-11T19-22-33.924Z.log)

Version: 24.09.08

**Comment by davidrapan** [comment]
You are using incorrect inverter profile.

You have to use inverter profile specific for your device which is deye_sg04lp3.yaml. 😉

**Comment by Milliamper** [comment]
You were right :D
It is now perfect!
