### ISSUE TITLE
Sofar 8.8KTL-X-G3 w/ sofar_tlx-g3 profile - CRC Error

### ISSUE THREAD

**Issue by biczu91** [davidrapan/ha-solarman#160]
Hello,
I made integration as in instruction but it doesn't work. It says "failure, trying to reconnect"
I'm not sure what I should upload to show the problem.

![obraz](https://github.com/user-attachments/assets/7972c032-3a9b-48b5-bcdd-461b1eef213a)

[home-assistant_solarman_2024-09-17T11-25-24.909Z.log](https://github.com/user-attachments/files/17027461/home-assistant_solarman_2024-09-17T11-25-24.909Z.log)

**Comment by davidrapan** [comment]
Hi @biczu91, disable this switch:
![tryb](https://github.com/user-attachments/assets/ba52d11f-a72d-44c8-8b1e-c9bbda730acc)

**Comment by biczu91** [comment]
Unfortunatelly still not working

**Comment by davidrapan** [comment]
Please enable debug logging and attach the file which it produces.

**Comment by biczu91** [comment]
[home-assistant_solarman_2024-09-17T19-51-05.087Z.log](https://github.com/user-attachments/files/17034247/home-assistant_solarman_2024-09-17T19-51-05.087Z.log)

**Comment by davidrapan** [comment]
Inverter is not responding to HA on 192.168.68.64.

**Comment by biczu91** [comment]
Oh well, I will try in the moring. I forgot it gone offline because it's dark already

**Comment by biczu91** [comment]
[home-assistant_solarman_2024-09-18T09-35-41.039Z.log](https://github.com/user-attachments/files/17041903/home-assistant_solarman_2024-09-18T09-35-41.039Z.log)

It still says cannot connect to 192.168.68.64, but I can connect to this IP via web browser

**Comment by davidrapan** [comment]
As I already said it looks exactly like the issue in #142 from @sanderbaks

**Solution was to ask support to update firmware of the inverter.**

**Comment by davidrapan** [comment]
Duplicate of #142
