### ISSUE TITLE
Deye 2/4mppt profile - Device Alert shows Error with value: 1900546, 1900548, 1900550

### ISSUE THREAD

**Issue by terzo33** [davidrapan/ha-solarman#171]
Hi @davidrapan , I always see this error message but actually there is no error, on solarman there is no warning

![Screenshot_20240923_073113_Home Assistant.jpg](https://github.com/user-attachments/assets/e2aa3f46-8b5b-4ca5-a034-f758780d3d60)

**Comment by davidrapan** [comment]
Hi @terzo33, does the Value 1.900.546 changes over time or does it stays the same?

**Comment by terzo33** [comment]
> Hi @terzo33, does the Value 1.900.546 changes over time or does it stays the same?

Alwasys the same in all 3 of my micro inverters

**Comment by davidrapan** [comment]
I mean it should be 0 which is OK state. And I have no idea what could this particular value mean... Does your official Solarman App shows anything useful in the Alarm/Fault notifications?

**Comment by terzo33** [comment]
Yes 4mppt profile, solarman app doesn't show me any errors

**Comment by davidrapan** [comment]
And if you browse the history of the notifications? Can you find something there?

**Comment by terzo33** [comment]
> And if you browse the history of the notifications? Can you find something there?

In solarman app?

![Screenshot_20240923_095206_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/e759964d-a69d-404c-8887-388a9632a955)

**Comment by davidrapan** [comment]
I could maybe add this values as an OK one for you when Solarman App does not see it as an error....

Anyway can I use this opportunity and ask you if sum of all your **PV1-4 Power** is ever higher than **Output Power**?

**Comment by terzo33** [comment]
> I could maybe add this values as an OK one for you when Solarman App does not see it as an error....
> 

Yes. I think so because i can't see any errors

**Comment by davidrapan** [comment]
Okay.

Could you please show me full sensor list of all your microinverters?

**Comment by terzo33** [comment]
![Screenshot_20240923_120713_Home Assistant.jpg](https://github.com/user-attachments/assets/c2638025-b617-423e-940d-e7ddf85a9bac)

![Screenshot_20240923_120717_Home Assistant.jpg](https://github.com/user-attachments/assets/7bd1c959-5f8d-4e51-ae09-1f441bc5f2dd)

![Screenshot_20240923_120721_Home Assistant.jpg](https://github.com/user-attachments/assets/f14a78d3-364f-4846-8715-6c0d11397e23)

![Screenshot_20240923_120725_Home Assistant.jpg](https://github.com/user-attachments/assets/bee26c3c-a0af-49f0-b099-9fdc2cfb1731)

**Comment by terzo33** [comment]
Where can i found register integration?

**Comment by davidrapan** [comment]
You need to have Developer Tools enabled in the HA and then there under **ACTIONS** you will find `Solarman: Read Holding Registers (Modbus Function Code 3)` Action. Select Device, input Register (80) and click **PERFORM ACTION**. And tell me the result. (Repeat for register number 82)

**Comment by terzo33** [comment]
> You need to have Developer Tools enabled in the HA and then there under **ACTIONS** you will find `Solarman: Read Holding Registers (Modbus Function Code 3)` Action. Select Device, input Register (80) and click **PERFORM ACTION**. And tell me the result. (Repeat for register number 82)

@davidrapan 

![Screenshot_20240923_135809_Home Assistant.jpg](https://github.com/user-attachments/assets/4e45d535-7a93-4fb3-9a8c-919c58d5588b)

![Screenshot_20240923_135746_Home Assistant.jpg](https://github.com/user-attachments/assets/8e007e4e-18d6-48e6-b5f5-d705a36d57b7)

**Comment by davidrapan** [comment]
Wonderful!

But to be 100% that they don't show any value could you maybe try to add into your profile and confirm it still does not show ay meaningful data?:
```
      - name: "Test Output"
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 0.1
        rule: 3
        registers: [0x0050, 0x0051]

      - name: "Test Input"
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 0.1
        rule: 3
        registers: [0x0052, 0x0053]
```

**Comment by davidrapan** [comment]
And also:
```
      - name: "Test PV1 Power"
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x00BA]
        icon: "mdi:solar-power-variant"

      - name: "Test PV2 Power"
        class: "power"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x00BB]
        icon: "mdi:solar-power-variant"
```

**Comment by terzo33** [comment]
> And also:
> ```
>       - name: "Test PV1 Power"
>         class: "power"
>         state_class: "measurement"
>         uom: "W"
>         scale: 1
>         rule: 1
>         registers: [0x00BA]
>         icon: "mdi:solar-power-variant"
> 
>       - name: "Test PV2 Power"
>         class: "power"
>         state_class: "measurement"
>         uom: "W"
>         scale: 1
>         rule: 1
>         registers: [0x00BB]
>         icon: "mdi:solar-power-variant"
> ```
> 

![Screenshot_20240923_141947_Home Assistant.jpg](https://github.com/user-attachments/assets/18510539-5104-411f-afc2-03b448d725b4)

![Screenshot_20240923_142011_Home Assistant.jpg](https://github.com/user-attachments/assets/ea4b4d98-b7b8-4527-a566-3b9c03e988ac)

![Screenshot_20240923_142020_Home Assistant.jpg](https://github.com/user-attachments/assets/b8f577da-bfb7-4fa0-bcd7-24cb2c930e92)

**Comment by davidrapan** [comment]
It should add the sensors into your device so show me list of the sensors please. 😉

**Comment by terzo33** [comment]
> It should add the sensors into your device so show me list of the sensors please. 😉 

![Screenshot_20240923_142505_Home Assistant.jpg](https://github.com/user-attachments/assets/17e529c8-61e9-49e7-9c31-b3833099ff87)

**Comment by davidrapan** [comment]
Does it Test PV1 Power anyhow corresponds to PV1 Power?

**Comment by terzo33** [comment]
> Does Test PV1 Power anyhow corresponds to PV1 Power?
> 
> Edit: Maybe if you change scale from 1 to 0.1?

![Screenshot_20240923_143246_Home Assistant.jpg](https://github.com/user-attachments/assets/131be0df-43f8-438f-bef1-c705b1c2173c)

**Comment by davidrapan** [comment]
Okay nevermind. It was worth the shot regardless. Thank you for your help! Very appreciated!

**Comment by terzo33** [comment]
It's a pleasure for me to help you

**Comment by davidrapan** [comment]
@terzo33, can you try [v24.09.23](https://github.com/davidrapan/ha-solarman/releases/tag/v24.09.23)?

**And easiest way how to clean up sensors after changes is to delete and re-add device after the update to newer version.**

**Comment by terzo33** [comment]
> @terzo33, can you try [v24.09.23](https://github.com/davidrapan/ha-solarman/releases/tag/v24.09.23)?
> 
> **And easiest way how to clean up sensors after changes is to delete and re-add device after the update to newer version.**

Interval update for pv information is always 5 min😔😔

**Comment by davidrapan** [comment]
Create another debug log file for me from at least one hour.

**Comment by davidrapan** [comment]
> Another error

That's really weird though... I wonder if is the register even correct?

**Comment by terzo33** [comment]
> > Another error
> 
> That's really weird though... I wonder if is the register even correct?

How can I help you?

**Comment by davidrapan** [comment]
> How can I help you?

That were just my thoughts...

Show me list of all sensors which you have there now so i can see if rest of the changes are okay.

**And record for me that debug log file from at least one hour please.** I'll check the data for PV sensors.

**Comment by terzo33** [comment]
@davidrapan another error🙈

![Screenshot_20240923_163836_Home Assistant.jpg](https://github.com/user-attachments/assets/aca9db0c-b8f9-425f-9ede-25146858dc41)

I don't understand

**Comment by terzo33** [comment]
@davidrapan 

debug log

![home-assistant_log.txt](https://github.com/user-attachments/files/17100911/home-assistant_log.txt)

**Comment by davidrapan** [comment]
Great, I'll look into it.

**Comment by davidrapan** [comment]
Hi @terzo33, try through that service call for reading registers read register number 109 and set the quantity to 4 (that means it will read registers from 109 to 112). Those registers contains voltage and current of your panels.

**Try to read them in like 10 seconds interval and see if the values changes every call or not.**

**Comment by davidrapan** [comment]
Little OT, could you also show me values of registers 15 and 19? Thank you!

**Comment by terzo33** [comment]
> Little OT, could you also show me values of registers 15 and 19? Thank you!

![Screenshot_20240924_125236_Home Assistant.jpg](https://github.com/user-attachments/assets/8e04b0dc-2775-4dfc-a57b-b853d3e1e56a)

**Comment by davidrapan** [comment]
> Yes. Change with 1/2 minutes interval

Can you show me?

**Comment by terzo33** [comment]
> > Yes. Change with 1/2 minutes interval
> 
> Can you show me?

See clock

This interval is 3 min but I saw also about 2 min

![Screenshot_20240924_133621_Home Assistant.jpg](https://github.com/user-attachments/assets/7c66c109-e7b4-464f-b7cd-6ccf5d96df60)

![Screenshot_20240924_133954_Home Assistant.jpg](https://github.com/user-attachments/assets/317f1644-774a-4840-9bdf-05f540dc98b4)

**Comment by terzo33** [comment]
> **To really have concrete results could you do 3 in a row with 1 min space in between each?**
> 
> Edit: Follow up question... Is the refresh period the same for all 3? **Current - Power - Voltage**? (When you look at list of all sensors)

Interval time is about 4/5 min.

I don't understand😓... other values of microinverter update with 5/6 seconds 

![Screenshot_20240924_134631_Home Assistant.jpg](https://github.com/user-attachments/assets/518a374e-4340-42b7-b311-cae438c42372)

![Screenshot_20240924_135003_Home Assistant.jpg](https://github.com/user-attachments/assets/b29dcaeb-7553-411d-af3d-90586d0f8fb3)

![Screenshot_20240924_135501_Home Assistant.jpg](https://github.com/user-attachments/assets/d3a28c02-c3f2-4361-81be-bfbb4ba3f929)

![Screenshot_20240924_135956_Home Assistant.jpg](https://github.com/user-attachments/assets/8fb87e62-a466-4fe5-94ff-7ad2ae5cad5f)

![Screenshot_20240924_140451_Home Assistant.jpg](https://github.com/user-attachments/assets/df0264fe-fed4-4130-802f-89ff85f39424)

**Comment by terzo33** [comment]
> Edit: Follow up question... Is the refresh period the same for all 3? **Current - Power - Voltage**? (When you look at list of all sensors)

Yes the same time but only for pv information.

**Comment by davidrapan** [comment]
> Yes the same time but only for pv information.

You mean Voltage and Current also updates with 5 min interval?

**Comment by terzo33** [comment]
> > Yes the same time but only for pv information.
> 
> You mean Voltage and Current also updates with 5 min interval?

Yes

**Comment by davidrapan** [comment]
Hey, open the folder with solarman code. Open file named api.py and on the row `210` **REPLACE** that row with following:
```
_LOGGER.debug(f"[{self.serial}] Returning {result_count} new values to the Coordinator. [Previous State: {self.get_connection_state()} ({self.state}), Values: {result}]")
```

Restart the HA and enable debug, log for a while and then attach it here, thanks.

**Comment by terzo33** [comment]
> Hey, open the folder with solarman code. Open file named api.py and on the row `210` **REPLACE** that row with following:
> ```
> _LOGGER.debug(f"[{self.serial}] Returning {result_count} new values to the Coordinator. [Previous State: {self.get_connection_state()} ({self.state}), Values: {result}]")
> ```
> 
> Restart the HA and enable debug, log for a while and then attach it here, thanks.

Doesn't work

![Screenshot_20240924_143824_Home Assistant.jpg](https://github.com/user-attachments/assets/dc146f49-1e8b-4313-8fee-359d5f33dde0)

![Screenshot_20240924_143908_Home Assistant.jpg](https://github.com/user-attachments/assets/e2f5eee0-3b06-4135-a289-947f2c982b90)

**Comment by davidrapan** [comment]
You accidentally removed these rows right after 210:
```
            now = datetime.now()
            self.state_interval = now - self.state_updated
            self.state_updated = now
            self.state = 1
```

**Comment by terzo33** [comment]
@davidrapan

I had to lighten the file

![home-assistant.txt](https://github.com/user-attachments/files/17119957/home-assistant.txt)

**Comment by davidrapan** [comment]
So yeah I mean you can see in the file that the data returned from the device are simply not refreshing with every request...

**Comment by davidrapan** [comment]
Every hint is pointing in that direction, yes. You have probably set from the Deye side update interval to 5m. **Try to write to Deye support and ask them to lower the update interval of your microinverters and see if that changes anything.**

**Comment by terzo33** [comment]
@davidrapan yes done. Just set to 60 sec

**Comment by davidrapan** [comment]
What do you mean? You have already set it to 60 s?

**Comment by terzo33** [comment]
> What do you mean? You have already set it to 60 s?

Yes. With deye support

**Comment by terzo33** [comment]
> What do you mean? You have already set it to 60 s?

![Screenshot_20240924_220234_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/2056610b-e7ac-4018-9e45-2a93f039fbce)

**Comment by terzo33** [comment]
I saw grid ac value with 5 sec update interval on HA. Can you check on debug?

**Comment by davidrapan** [comment]
Yes there some occasions when for example Grid Voltage changes from 236V to 235V and then immediately back to 236V in 5 s interval.

**Comment by terzo33** [comment]
@davidrapan i don't understand why "update interval" for grid voltage is about 5/10 sec and for other values is 4/5 minutes 🤷‍♂️

https://github.com/user-attachments/assets/9f8b3a8b-d8cd-4ff7-95e0-237b77659254

**Comment by davidrapan** [comment]
I honestly don't get it either.

_The way the indication of `? seconds/minutes ago` change works is that it will update only if the value displayed changes. So because the value given by the inverter does not change it displays different update periods._

**Comment by terzo33** [comment]
@davidrapan Another error :(

![Screenshot_20240928_105631_Home Assistant.jpg](https://github.com/user-attachments/assets/4397c487-9516-4cc1-822a-0d3da583eff4)
