### ISSUE TITLE
Deye 4MPPT - missing values - 24.09.2x

### ISSUE THREAD

**Issue by Wubarius** [davidrapan/ha-solarman#173]
**Describe the bug**
Version 24.09.08 - with "deye_4mppt.yaml" - works fine
Version 24.09.20 - no values
Version 24.09.22 - no values

"Total AC Output Power (Action)" -  missing
There are no more values ​​for the current PV production.
Or the entity has changed to "Output Power"
Is that what you want?
If so - I really have to adjust a lot of things.

**To Reproduce**
Update Solarman from 24.09.08 to latest version

**Expected behavior**
Why were the entities changed and the old ones remained but without values.
- Total AC Output Power (Action) - unavailable
- Output Power

**Screenshots**
see 3 files from device "Garage"

**Metadata:**
Version: 24.09.08 - yaml version 12.08.2024
Version: 24.09.22 - yaml version 17.09.2024

I replaced the file "deye_4mppt.yaml" with the old one.
New entities are displayed without values
- Output Frequency
- Output Power
- Total Production 3 & 4

24.09.08
![solarman_240908-01](https://github.com/user-attachments/assets/2df88955-de31-46d5-b798-4a6bdb48770f)

24.09.22
![solarman_240922-01](https://github.com/user-attachments/assets/4a1f2643-9f8b-4dfd-8991-1daab98f6e03)

24.09.22 - with old yaml
![solarman_240922-old-yaml](https://github.com/user-attachments/assets/6783a841-3b40-47ae-885e-251d0d871efc)

**Comment by davidrapan** [comment]
Hi @Wubarius, yes it is. You can still use the older version of the file as custom profile if it's too much problem for you. 😉

**Comment by Wubarius** [comment]
Hi @davidrapan,

thanks for the quick reply.

I'll probably keep the old ones. I'd have to change too much if the entity was renamed.

I've now integrated the new one - but I'm still using the old ones.

**Comment by davidrapan** [comment]
Yeah, sorry that I totally forgot to write about those changes in the Release Note. That's big fail from my side. That shouldn't have happened. Another fail is that i messed up the new entity names anyway. Guess I need a break, lol.

Again sorry.
