### ISSUE TITLE
DEYE 2MPPT: AC Output Values on longer available

### ISSUE THREAD

**Issue by PiperNigrum** [davidrapan/ha-solarman#174]
After the last update two Sensors are no longer available:

![image](https://github.com/user-attachments/assets/23ac9d54-6e33-402e-a8da-75abcd3bfa7f)

![image](https://github.com/user-attachments/assets/0e2a0495-5d44-47ae-b98c-a67aece2c42b)

**Comment by CrazyUs3r** [comment]
You can solve them easily because they have been renamed

**Comment by davidrapan** [comment]
Yes exactly. I will be commit some more changes in to the repo which will contain some additional renames but brand new entities as well.

**Comment by PiperNigrum** [comment]
Hey together,
thanks for the Input.
Both new entities are in the list 🤓
