### ISSUE TITLE
Sofar 5KTLM-G3 w/ sofar_lsw3 profile - No (zeroes) values

### ISSUE THREAD

**Issue by jeffersonbernardo1981** [davidrapan/ha-solarman#176]
Hello, I'm having some difficulty with ref. integration. I use the sofar_lsw3 inverter, and I've already installed and uninstalled it several times and the sensors just stay at zero, has anyone experienced this and managed to solve it?
![Captura de tela 2024-09-23 164428](https://github.com/user-attachments/assets/29680b39-85b8-4848-a881-79d6a0d93a12)
![Captura de tela 2024-09-23 164428](https://github.com/user-attachments/assets/c1f2e9ea-727f-4e52-b6c6-302b86290992)
 version: 24.09.23

**Comment by davidrapan** [comment]
Hi @jeffersonbernardo1981, what exact device and model you have?

**Comment by jeffersonbernardo1981** [comment]
Hi David, follow the label data for the Sofar Solar inverter, Model 5KTLM-G3.
![WhatsApp Image 2024-09-24 at 07 22 54](https://github.com/user-attachments/assets/8d3598cc-336c-41a8-a05e-416d0ff24b1b)

**Comment by davidrapan** [comment]
And did you also try it with other profiles? For example: `sofar_tlx-g3.yaml` or `zcs_azzurro-ktl-v3.yaml`?

**Comment by jeffersonbernardo1981** [comment]
Yes, I tried them all and the only one I have feedback on is sofar_lsw3_yaml, the others give an error as shown in the image:
![Captura de tela 2024-09-24 0957521](https://github.com/user-attachments/assets/444d21c2-abf7-4533-8495-3ec223dbd592)

**Comment by davidrapan** [comment]
Could you enable debug logging and load it with `sofar_tlx-g3.yaml` and attach the debug log here? Thank you.

**Comment by jeffersonbernardo1981** [comment]
David, follow the logs!
[home-assistant_solarman_2024-09-24T15-26-38.265Z.log](https://github.com/user-attachments/files/17116966/home-assistant_solarman_2024-09-24T15-26-38.265Z.log)

**Comment by jeffersonbernardo1981** [comment]
David, I managed to perform a firmware update directly with the manufacturer, and I did the entire process, uninstalled the integration and reinstalled it again, I am getting feedback on some data but others do not follow the prints.
![SmartSelect_20240924_145303_Home Assistant](https://github.com/user-attachments/assets/c1f34d0e-af1b-4bfe-a682-a8d8fc35ab97)
![SmartSelect_20240924_145406_Home Assistant](https://github.com/user-attachments/assets/43413f84-a125-448b-9cdc-735152e3559a)
![SmartSelect_20240924_145508_Home Assistant](https://github.com/user-attachments/assets/065cd55b-60fe-413b-b673-1bb8cb92ad1e)

**Comment by davidrapan** [comment]
Great! That's a progress! Which profile did you used in this case?

It's still possible that your device uses some specific registers for some values so you will need some new profile specifically tuned for your device.

**Anyway which sensor values do work and which does not?**

**Comment by jeffersonbernardo1981** [comment]
I'm using this profile, sofar_tlx-g3.yaml.
