### ISSUE TITLE
Possible for v4

### ISSUE THREAD

**Issue by jonasradke** [davidrapan/ha-solarman#18]
Hey is it somehow possible to use this with v4 protocol?
That would be so awesome :)

**Comment by davidrapan** [comment]
Hi, someone here already said that he used it with V4 but I guess you'll have to try it to know for sure.

I don't really know the differences between versions of the protocol.. :/

Have fun!

**Comment by jonasradke** [comment]
Yes it works for me :)

**Comment by jonasradke** [comment]
It's serial number 23*** and deye inverter
