### ISSUE TITLE
Microinverter Starting Voltage Upper/Lower Limit -> Unknown

### ISSUE THREAD

**Issue by terzo33** [davidrapan/ha-solarman#181]
@davidrapan status unknown for "starting voltage" microinverter

![Screenshot_20240928_105508_Home Assistant.jpg](https://github.com/user-attachments/assets/b99186a3-2566-437f-9c35-30adca5a65e7)

**Comment by davidrapan** [comment]
Hi @terzo33, show me please registers 32 and 33.

Thanks!

**Comment by terzo33** [comment]
> Hi @terzo33, show me please registers 32 and 33.
> 
> Thanks!

![Screenshot_20240928_110914_Home Assistant.jpg](https://github.com/user-attachments/assets/eac13a53-3ad5-4b1f-ac70-16f54cd9ffc3)

**Comment by davidrapan** [comment]
Fuh, those values does not make much sense in terms of what documentation says.. :-/

**Can you somehow find out to which values is Starting voltage Upper/Lower Limit is really set on your device?**

**Comment by terzo33** [comment]
> Fuh, those values does not make much sense in terms of what documentation says.. :-/
> 
> **Can you somehow find out to which values is Starting voltage Upper/Lower Limit is really set on your device?**

On my inverter or on battery?

**Comment by davidrapan** [comment]
> On my inverter or on battery?

Microinverter.

**Comment by terzo33** [comment]
> > On my inverter or on battery?
> 
> Microinverter.

but I don't think you can connect the battery to the micro inverter. there is no connection

**Comment by davidrapan** [comment]
This is not about the battery at all.

**Comment by terzo33** [comment]
> > On my inverter or on battery?
> 
> Microinverter.

On which page can I see this value?

**Comment by davidrapan** [comment]
Probably in device parameters?

**Comment by terzo33** [comment]
> Probably in device parameters?

I don't know where to look for these values. even if sularman I can't find anything. but I can't find the ones you entered on the home assistant like the soft start and others.

![Screenshot_20240929_075018_Samsung Internet.jpg](https://github.com/user-attachments/assets/0f34ed66-ae99-4bd9-9e7f-05b39cddee19)

![Screenshot_20240929_075145_Samsung Internet.jpg](https://github.com/user-attachments/assets/c0c5464b-9bda-4ec8-857d-3b4f5341aec2)

**Comment by CrazyUs3r** [comment]
At my sunm80g3 is the value all time zero


![Screenshot_20240929_094843_Home Assistant](https://github.com/user-attachments/assets/546ada6f-973d-4a44-9020-a73c82e19e2d)

**Comment by davidrapan** [comment]
@terzo33, only in Solarman App.

**Comment by terzo33** [comment]
> @terzo33, only in Solarman App.

I can't see nothing

![Screenshot_20240929_113540_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/60c0ff4a-dca5-4723-8ff5-958d5a880b0c)

![Screenshot_20240929_113543_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/4736d251-6adc-4cbc-a4e2-e0002c998337)

![Screenshot_20240929_113547_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/97e77ce5-fc86-4aa2-84d0-d7d4109cd308)

**Comment by davidrapan** [comment]
There should be somewhere also configurable parameters. Which you can change from the App.

**Comment by terzo33** [comment]
@davidrapan I can't find them. Do you have any suggestions where to look?

**Comment by CrazyUs3r** [comment]
Right Upp the 3 ...

**Comment by terzo33** [comment]
> Right Upp the 3 ...

What mean?

**Comment by CrazyUs3r** [comment]
![Screenshot_20240929_122847_Firefox](https://github.com/user-attachments/assets/e82bf908-9e15-463f-81f2-2bac328e96e0)

**Comment by terzo33** [comment]
@davidrapan @CrazyUs3r 

![Screenshot_20240929_125448_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/a230065a-1823-4c4b-aa3c-1f59232d80bd)

![Screenshot_20240929_125500_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/87f8f430-d930-45c7-9772-7b475574ee85)

![Screenshot_20240929_125503_SOLARMAN Business.jpg](https://github.com/user-attachments/assets/fd84eced-8ff1-4186-b085-644ce549ddf5)

**Comment by davidrapan** [comment]
That's under "Controllo remoto"?

It's as Device Control in English.

**Comment by terzo33** [comment]
> That's under "Controllo remoto"?
> 
> It's as Device Control in English.

https://github.com/user-attachments/assets/b4fe0b0f-e037-4676-b671-3a814c8b990f

**Comment by davidrapan** [comment]
What if you look at it on the website and not the app?

**Comment by davidrapan** [comment]
[fix: Removed Starting Voltage * from Deye 2/4mppt](https://github.com/davidrapan/ha-solarman/commit/cb98702055ffcb84c1a1b1cec2bd97d4891c6081)
