### ISSUE TITLE
Today's Battery Charge resets at wrong time

### ISSUE THREAD

**Issue by Jeffaffa** [davidrapan/ha-solarman#184]
Hi,

I have an issue that my "Today's Battery Charge" and "Today's Battery Discharge" reset everyday at 6pm (18:00) instead at midnight. Is there somehow I can change this?

I use the pylontech_Force-H.yaml parameter definitions.

<img width="566" alt="Screenshot 2024-09-29 at 07 40 27" src="https://github.com/user-attachments/assets/76d846a5-936a-4347-bd76-9ce25578fc3e">

**Comment by davidrapan** [comment]
Hi @Jeffaffa, your battery have probably incorrect time set.

**Comment by Dubists** [comment]
@Jeffaffa: The system time of your Inverter is incorrect.

**Comment by Jeffaffa** [comment]
Thank you.
