### ISSUE TITLE
Deye Battery Grid Charging Start missing units

### ISSUE THREAD

**Issue by rromrrom** [davidrapan/ha-solarman#193]
**Describe the bug**

deye_hybrid.yaml
No **uom** for the _"Battery Grid Charging Start Voltage" and "Battery Grid Charging Start"_

Should be "V" and "%".

**Screenshots**
![image](https://github.com/user-attachments/assets/191fe03e-22c3-4780-ba15-66539ee8cbd2)

**Metadata:**
Version: 24.09.27

**Comment by davidrapan** [comment]
[fix: Deye Battery Grid Charging Start units](https://github.com/davidrapan/ha-solarman/commit/9486725e092af397d98a24cf9c273642cefaf377)
