### ISSUE TITLE
New wiki page for new devices

### ISSUE THREAD

**Issue by gardiol** [davidrapan/ha-solarman#213]
I created this page as a starting point:
https://github.com/gardiol/ha-solarman-wiki/edit/master/Add-New-Device.md

i have no idea how to actually open a pr for the wiki?

**Comment by davidrapan** [comment]
> i have no idea how to actually open a pr for the wiki?

I don't think it's possible so...

**Comment by davidrapan** [comment]
Also feel free to create your own wiki with whatever documentation or guide you want and I'll add link to it from wiki in this repo!
