### ISSUE TITLE
HOMEASSISTANT GREEN UPDATE VERSION OS 13.2

### ISSUE THREAD

**Issue by sentink** [davidrapan/ha-solarman#250]
### Description

Good morning, this morning HomeAssistant Green was updated to version 13.2 and Solarman has stopped working, all entities appear deactivated.

### Reproduction Steps

![image](https://github.com/user-attachments/assets/be73baae-033b-43e2-8c5d-f449daabf56a)

![image](https://github.com/user-attachments/assets/f16e0a8c-064c-442b-a6eb-9d4307fe1fbf)

![image](https://github.com/user-attachments/assets/af187011-11d9-42f2-b48c-7e17288c9b15)

![image](https://github.com/user-attachments/assets/89312ec4-7d45-426e-a1a2-a8d204de5f27)

### Log

No debug log is generated

### Version

v24.10.31

**Comment by sentink** [comment]
Solarman has been updated to version 24.11.02, but it still doesn't work

![image](https://github.com/user-attachments/assets/9a0c9f60-4e03-4f87-99cc-872a2b0e88b8)

**Comment by Dawid46** [comment]
will it be fixed ?

**Comment by sentink** [comment]
Good afternoon David, no, it still doesn't work

![image](https://github.com/user-attachments/assets/16cbc03d-a441-4d97-8b73-d9c85d1d0b89)

**Comment by davidrapan** [comment]
You need to enable debug logging, reload the integration and then attach the file here.

**Comment by sentink** [comment]
Good night

Registrador: homeassistant.config_entries
Fuente: config_entries.py:594
Ocurrió por primera vez: 17:51:37 (3 ocurrencias)
Última vez registrado: 23:12:02

Error setting up entry Inverter1 for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/__init__.py", line 58, in async_setup_entry
    inverter = Inverter(inverter_host, serial, inverter_port, mb_slave_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/api.py", line 26, in __init__
    super().__init__(address, serial, port = port, mb_slave_id = mb_slave_id, logger = _LOGGER, auto_reconnect = AUTO_RECONNECT, socket_timeout = TIMINGS_SOCKET_TIMEOUT)
  File "/usr/local/lib/python3.12/site-packages/pysolarmanv5/pysolarmanv5_async.py", line 65, in __init__
    self.data_wanted_ev = Event()
                          ^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 93, in Event
    return Event(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 331, in __init__
    self._cond = ctx.Condition(ctx.Lock())
                               ^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system

**Comment by davidrapan** [comment]
Duplicate of #39

**Comment by davidrapan** [comment]
> OSError: [Errno 30] Read-only file system

ssh into your ha and run: ha core rebuild

**Comment by sentink** [comment]
Thanks for the second time David, I'm a newbie to HA, I'll record this in case it happens again in another update.
