### ISSUE TITLE
Wrong PV1-4 Power Value

### ISSUE THREAD

**Issue by ugath** [davidrapan/ha-solarman#251]
### Description

Since last Update(?) PV1-4 Power schows the same value as PV1-4 Voltage.
deye2mppt and deye4mppt

### Reproduction Steps

![Screenshot_20241104_193904_Home Assistant](https://github.com/user-attachments/assets/9eb0ac87-bb4e-429c-997d-6c13dfcffcaa)

### Log

No Logfile

### Version

v24.11.01

**Comment by davidrapan** [comment]
This issue has been fixed in v24.11.02.
