### ISSUE TITLE
Wrong data battery charge on Deye Hybrid Inverter 

### ISSUE THREAD

**Issue by wifi75** [davidrapan/ha-solarman#253]
### Description

Hello, for several days I have encountered a problem in the battery charge data readings.
I have a 15.3 Kwh 300Ah battery, this morning it was completely flat, with a (20% residual about 3.2Kwh). As soon as the production of my PV began it started charging. In home assistant it shows the current charge and it is about 6.2 Kwh. Incorrect value, because connecting directly to the BMS it is almost charged about 285Ah.

see last scrernshot, only the sensor sensor.solar_battery It seems to give a true value

### Reproduction Steps

![image](https://github.com/user-attachments/assets/e2eb8f3c-11e3-42fc-8acd-e18135e88141)
![image](https://github.com/user-attachments/assets/bfa4ca8d-a9a8-4a82-a043-8d337806c8b1)

### Log

[home-assistant_solarman_2024-11-05T10-46-16.064Z.log](https://github.com/user-attachments/files/17631086/home-assistant_solarman_2024-11-05T10-46-16.064Z.log)

### Version

v24.11.02

**Comment by davidrapan** [comment]
But does the Total Battery Charge work?

**Comment by wifi75** [comment]
I'll wait for the charge to finish and then I'll show you the values..

**Comment by wifi75** [comment]
Ok Davide, sorry, but after your last update the problem seems to have gone away!
the values ​​all seem to be correct

**Comment by davidrapan** [comment]
Sure no worries.
