### ISSUE TITLE
Add more extra load device 

### ISSUE THREAD

**Issue by wifi75** [davidrapan/ha-solarman#255]
### Is your feature request related to a problem?

hello it is possible add more device like the ones marked with the green circle?
I noticed that there is space and it would be nice to have other devices that show their consumption...

![image](https://github.com/user-attachments/assets/73a33414-2fa5-4850-b414-b0df0ab9348b)

### Describe the solution you'd like

add extra load device

### Describe alternatives you've considered

f

**Comment by davidrapan** [comment]
Hello @wifi75, this request has nothing to do with this integration.

But to answer you question in general.. Yes, you can certainly do that if you buy and connect some power meters (e.g. Shelly is really good brand in that matter) alongside you devices you want to measure. **The inverter only provides data about itself and has no way of knowing about your connected appliances**...

**Comment by wifi75** [comment]
Hi, maybe I explained myself poorly, I already use shelly to monitor those devices, the fact is that I would like to add the dryer and the oven, but there is no possibility of adding 2 more devices...

**Comment by davidrapan** [comment]
I don't know the integration you are showing in the picture. You will have to ask on their page.

**Comment by wifi75** [comment]
I'm really in bad shape.. sorry sorry!!!

**Comment by davidrapan** [comment]
No worries!
