### ISSUE TITLE
Missing custom file after update

### ISSUE THREAD

**Issue by mamo-nick** [davidrapan/ha-solarman#259]
### Description

I have a custom modbus configuration file located in inverter_definition folder. This file is deleted with each update.
I recommend updating only changed files.

### Reproduction Steps

1. Create a file and save it in inverter_definition. 
2. Run the integration update
3. Check the existence of the file

### Log

n/a

### Version

v24.11.02

**Comment by PV-Joe** [comment]
Add a custom folder and put your file in there. This folder won‘t be deleted when updating.

Like this…

![IMG_6119](https://github.com/user-attachments/assets/025f3021-bfd4-446d-8933-e4f08af8a05b)
