### ISSUE TITLE
DEYE SUN-8K-G05 yaml file

### ISSUE THREAD

**Issue by folny** [davidrapan/ha-solarman#263]
Hi I have a deye sun-8k-g05 inverter and I can't read the power on PV1 and PV2, what are the addresses to read the power ?. Does anyone have a yaml file for this inverter where all the parameters can be read ?.

**Comment by davidrapan** [comment]
Hi @folny, so any of the already present `deye_*` profiles does not work?

**Comment by davidrapan** [comment]
Enable debug logging and attach the file here.

**Comment by folny** [comment]
Okay, I'll add the debug file tomorrow.

**Comment by folny** [comment]
Hi

So I played around a bit today and it seems the data is now correct but I would like to know how I can read the values ​​from the smart meter connected to the inverter so I can find out the household consumption and the energy that goes from the grid and into the grid.
![Deye Data](https://github.com/user-attachments/assets/e3a1811a-2495-4a40-8055-07972a7f3d74)

**Comment by davidrapan** [comment]
Try it with `deye_hybrid.yaml` profile then. String and Hybrid profiles are essentially the same but the String has fewer registers read.

**Comment by folny** [comment]
I have already tried this option, but the data I need is incorrect.

![Deye Data 2](https://github.com/user-attachments/assets/85d344c9-2708-4e7a-9f6e-3698937c436b)

**Comment by davidrapan** [comment]
What about 203, 204?

**Comment by folny** [comment]
Yes, it should be those registers, but I didn't have time to try it today, I'll try it tomorrow and let you know.

**Comment by folny** [comment]
So today I added more registers to the file and it seems that everything is working as it should. So I'm adding my file here and I hope it helps someone in the future.

[deye_sun_g05_power_flow_card.zip](https://github.com/user-attachments/files/17818607/deye_sun_g05_power_flow_card.zip)

![Deye Power Panel](https://github.com/user-attachments/assets/8dcfc566-be31-483c-962c-867efc4084ce)

**Comment by davidrapan** [comment]
I think that Load Power should be unsigned.

[feat: Load & Grid Power for Deye String](https://github.com/davidrapan/ha-solarman/commit/12c5d45704764a802a9d6c8a012e6ad28bc760dd)

**Comment by folny** [comment]
There are more irrelevant values ​​but I left them there.
