### ISSUE TITLE
Error when adding integration

### ISSUE THREAD

**Issue by rp2019433** [davidrapan/ha-solarman#266]
### Description

After installing ha-solarman through HACS, adding integration brings this error:

![image](https://github.com/user-attachments/assets/5e74f38a-5f2d-47a8-b96d-186c436d42c0)

### Reproduction Steps

1.Had [StephanJoubert/home_assistant_solarman](https://github.com/StephanJoubert/home_assistant_solarman) installed previously. 
2. Removed [StephanJoubert/home_assistant_solarman](https://github.com/StephanJoubert/home_assistant_solarman) installation.
3. Installed https://github.com/davidrapan/ha-solarman.

### Log

![image](https://github.com/user-attachments/assets/015366b7-87dc-4789-bea6-448e44f2d75d)

### Version

v24.11.02

**Comment by CrazyUs3r** [comment]
ssh into your ha and run: ha core rebuild

**Comment by rp2019433** [comment]
> ssh into your ha and run: ha core rebuild

Hi. Did it but the error persist. Tried to remove, reinstall and rebuild as well, but it didn't work.


```
Logger: homeassistant.config_entries
Source: config_entries.py:3249
First occurred: 4:50:26 PM (1 occurrences)
Last logged: 4:50:26 PM

Error occurred loading flow for integration solarman: No module named 'pysolarmanv5'
```

**Comment by davidrapan** [comment]
It's a problem with HA OS or core, don't remember which one exactly, upgrade or downgrade should fix that.

**Comment by rp2019433** [comment]
> It's a problem with HA OS or core, don't remember which one exactly, upgrade or downgrade should fix that.

Hi. I've tested in two HA instances, both with same software version as below:

```
Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
Front-end 20241106.2
```

One of the instances had Solarman StephanJoubert installed, and  is the one that is experiencing problem with "Config flow could not be loaded".

The other one, fresh install, ha-solarman was installed correctly.

**Comment by davidrapan** [comment]
Yes, I told you it's bug in HA and the act of downgrade/upgrade will fix it.

**Comment by rp2019433** [comment]
> Yes, I told you it's bug in HA and the act of downgrade/upgrade will fix it.

Got it now. Thanks.

`ha core update --version XXX` to downgrade and later upgraded.
