### ISSUE TITLE
Configuring an existing device causes sensor naming issue

### ISSUE THREAD

**Issue by gedger** [davidrapan/ha-solarman#28]
If you configure an existing device the prefix name is not shown in the dialogue window. On pressing submit all sensors are renamed with the "None" prefix.

<img width="697" alt="Screenshot 2024-07-22 at 17 34 17" src="https://github.com/user-attachments/assets/c7a12652-84bc-4576-930e-5ce604d8caca">
<img width="408" alt="Screenshot 2024-07-22 at 17 34 37" src="https://github.com/user-attachments/assets/695e0796-b9a9-47a7-ae5a-572c33bb0db6">

**Comment by davidrapan** [comment]
Yes I noticed that too today. ConfigFlow and OptionsFlow still works (for me) in a mysterious ways. Common sense says that name should not be there as it's updateable from menu under those dots but I guess I'll put it back.

Thanks!

**Comment by davidrapan** [comment]
[3808a54](https://github.com/davidrapan/ha-solarman/commit/3808a5412042650b35828bcd1debd2c070f7d390)

**Comment by gedger** [comment]
Fixed although as you say it does make more sense to hide the name and use the rename function from the ... menu.

**Comment by davidrapan** [comment]
Yep exactly, will see in the future if I found out how it's supposed to work. Development documentation for HA is I don't wanna say bad, it's okay. But it has some holes here and there...

Cheers!
