### ISSUE TITLE
Deye Hybrid missing Microinverter Power sensor

### ISSUE THREAD

**Issue by terzo33** [davidrapan/ha-solarman#282]
Hi @davidrapan, with new upgrade I can't see anymore microinverter power value

![Screenshot_20241205_092843_Home Assistant.jpg](https://github.com/user-attachments/assets/3dbf0472-21d5-4401-88f1-407bc40658da)

**Comment by davidrapan** [comment]
I'm working on feature which will rename entity according to selected mode of the I/O so wait a bit. 😉

**Comment by terzo33** [comment]
> I'm working on feature which will rename entity according to selected mode of the I/O so wait a bit. 😉

Awesome 😍

**Comment by davidrapan** [comment]
Feature should be up and running in [feat: Gen/SL/MI sensors named by selected IO mode](https://github.com/davidrapan/ha-solarman/commit/bf4d3e9942780ded8712d5fc248b12d2462cc220)
