### ISSUE TITLE
Configuration Dialogue has an unnamed field

### ISSUE THREAD

**Issue by gedger** [davidrapan/ha-solarman#29]
Configuration shows a field with no identification or description.

<img width="231" alt="Screenshot 2024-07-22 at 17 40 32" src="https://github.com/user-attachments/assets/5f45a9b6-af34-45b8-9c8d-c96d2d6637e3">

**Comment by davidrapan** [comment]
That's a modbus id right there. I'll check it. Thanks.

**Comment by davidrapan** [comment]
[3808a54](https://github.com/davidrapan/ha-solarman/commit/3808a5412042650b35828bcd1debd2c070f7d390)

**Comment by gedger** [comment]
No change, still unnamed.

**Comment by davidrapan** [comment]
Does you translation files containt "inverter_mb_slave_id" string?

**Comment by gedger** [comment]
Confirmed translation is there. It's not really an issue so park it until someone else reports it. Could be something odd about my system.

**Comment by gedger** [comment]
And magically it has now appeared 😕

**Comment by davidrapan** [comment]
Magic! hehe
