### ISSUE TITLE
SOFAR LSW3 setup/connection problem

### ISSUE THREAD

**Issue by maniac2003** [davidrapan/ha-solarman#301]
### Description

Hi all,

I've got the following error during installation:
![image](https://github.com/user-attachments/assets/8ca3c128-ff4c-4500-9a54-32b7e9abe2d0)

Any ideas?

Regards
 Eike

### Version

24.12.08_1

Stick Firmware:
LSW3_15_270A_1.68

HomeAssistant:
Core
2024.12.1
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.6

**Comment by davidrapan** [comment]
Hi @maniac2003, that means that this profile is not for your device (contains registers which are not used in your device).

**Comment by maniac2003** [comment]
Hi @davidrapan, thanks for the fast reply.

I have a Sofar inverter HYD 10KTL-3PH-PRO with logger LSW3.
The profile I have chosen is sofar_lsw3.yaml.

Is the inverter / logger compatible with your integration?

Regards
 Eike

**Comment by davidrapan** [comment]
You should proly try `sofar_g3hyd.yaml`.

**Comment by maniac2003** [comment]
Perfect, it's working now, thanks.
