### ISSUE TITLE
Release 24.12.10_3 Connection flapping

### ISSUE THREAD

**Issue by gedger** [davidrapan/ha-solarman#320]
### Description

After upgrading to 24.12.10_3 the connection never stabilises after the inverter comes back on-line. Reverting back to 24.12.10 the connection remains stable. Chart below shows connection state, the longer green Connected at 9:01 was after down grading. Reverting back to 24.12.10_3 at 9:04:30 issue re-appears.

<img width="1194" alt="Screenshot 2024-12-13 at 09 08 36" src="https://github.com/user-attachments/assets/6e24a328-4802-4c7f-ae82-1684e78f41f0" />

### Reproduction Steps

Upgrading to 24.12.10_3 causes issue, reverting to 24.12.10 fixes.

Inverter Solis using custom profile.

### Log

[home-assistant_solarman_2024-12-13T09-07-53.893Z.log](https://github.com/user-attachments/files/18124008/home-assistant_solarman_2024-12-13T09-07-53.893Z.log)

### Version

24.12.10_3

### Home Assistant Version

2024.11.3

**Comment by davidrapan** [comment]
Hi @gedger, it looks like there is an error every other request w/ empty requests list. I don't know how this could have happened, but I'll look into it.

**Comment by davidrapan** [comment]
Could you try inject this code snippet into the `get` method in `api.py`:
```
        if scheduled_count == 0:
            return result
```
on the row 226, right after that `_LOGGER.debug(...` ?

**Comment by davidrapan** [comment]
Should be fixed in [v24.12.14](https://github.com/davidrapan/ha-solarman/releases/tag/v24.12.14)
