### ISSUE TITLE
Add SUN300G3-EU-230 to list of supported devices

### ISSUE THREAD

**Issue by pschneider87** [davidrapan/ha-solarman#335]
### Is your feature request related to a problem?
no

### Describe the solution you'd like
I can confirm that the SUN300G3-EU-230 (e.g. https://solarv.de/Deye-Mikrowechselrichter-SUN300G3-EU-230-mit-BetteriBC01-Stecker) is working fine with deye_micro.yaml and this integration. you might add this to the supported devices list.

### Describe alternatives you've considered
leave it out and keep people curious about it :-)

**Comment by davidrapan** [comment]
Hi @pschneider87, it was there already but the rated power range was not correct.

Was SUN600/800/1000G3-EU-230 instead of SUN300/500/600/800/1000G3-EU-230. Thanks for pointing that out. 😉
