### ISSUE TITLE
Deye - Grid Side INV Meter2

### ISSUE THREAD

**Issue by Golempl** [davidrapan/ha-solarman#341]
### Is your feature request related to a problem?

Would be nice to read this additional meter.

### Describe the solution you'd like

Just add Grid Tie Inv Meter2

### Describe alternatives you've considered

No alternative.

**Comment by davidrapan** [comment]
I have no idea what this device is. Do you have a  rtu documentation?

**Comment by Golempl** [comment]
This is additional meter when u tick Grid Side INV meter2
It works with normal CT's but also provides generation data from AC coupled inverters. Deye Cloud include this data. I think it's possible but need possibly modebus address
![obraz](https://github.com/user-attachments/assets/a19b97a4-44d6-495a-b086-3d55b83d34d0)

**Comment by davidrapan** [comment]
You should have said it's for Deye. It looked like you are requesting addition of new device. 😉

So you want to be able to configure what's on this page?

**Comment by Golempl** [comment]
No configuration is needed. I just want to access the readings from the additional meter connected to the Deye. I have the Deye 12k-SG04LP3-EU, and with the latest firmware (C04B/F150), it is now possible to use an extra meter. It would be great to have the data from this meter in Home Assistant, specifically the kWh value and name, such as: Grid Tie Meter2.

I'm not entirely sure if the following address is correct, but it might be worth checking or consulting Deye support for the correct one:

    536: Daily energy generation by the generator (R, unit: 0.1 kWh)
    537: Low byte of the total energy generated by the generator (R, unit: 0.1 kWh)
    538: High byte of the total energy generated by the generator (R, unit: 0.1 kWh)

**Comment by davidrapan** [comment]
Ah I see, but those are already there. It's from generator port and it's called `Total Generation`.
