### ISSUE TITLE
Totals w/ zeroes shows unknown instead

### ISSUE THREAD

**Issue by aLAN-LDZ** [davidrapan/ha-solarman#343]
### Description

Hey,

I'm just starting my adventure with Deye. I haven't sent any energy to the grid yet. The daily export indicator shows 0kWh, while the total export indicator is unknown. This is why the energy card doesn't work properly. Can it initialize as 0? I set 0 in the developer settings, unfortunately it immediately changed to unknown

Taking advantage of the opportunity. Great integration. Merry Christmas!

### Reproduction Steps

There was never any export

### Log

no log

### Version

24.12

### Home Assistant Version

24.12

**Comment by davidrapan** [comment]
No, totals will show unknown instead of 0 as a failsafe because there are some occasions during full reboot when it reports 0 which causes resets in the HA sensor and when it returns current real value right after and essentially doubles your values every time this happens.
