### ISSUE TITLE
Deye microinverter 800W problem

### ISSUE THREAD

**Issue by radektkacik** [davidrapan/ha-solarman#345]
### Description

Problem in HA log

### Reproduction Steps

Added new microinverter

### Log

Config entry 'Deye 1' from integration solarman has an invalid unique_id '3925096234' of type int when a string is expected, please create a bug report at https://github.com/davidrapan/ha-solarman/issues

### Version

24.12.08

### Home Assistant Version

2024.12.1

**Comment by CrazyUs3r** [comment]
Update too 12.22
