### ISSUE TITLE
Battery SOH, Today Life Cycles and Total Life Cycles are calculated incorrectly for Deye BOS GM5.1 + BMS HVB750V/100A

### ISSUE THREAD

**Issue by iwannatalk** [davidrapan/ha-solarman#350]
### Description

Hello,

The following sensor values are incorrectly calculated for Deye BOS GM5.1 + BMS HVB750V/100A:
- Battery SOH
- Today Life Cycles
- Total Life Cycles

Im not sure whether it is a bug or a feature request (cause maybe noone had a chance to test it with Deye hith voltage batteries).

I have BMS HVB750V/100A + 8 instances of Deye BOS GM5.1 and was wondering why my battery when charging from (lets say from todays example) from SOC 12% till 90% takes 3.37 lifecycles :) and totally 58 days of work already used 142 lifecycles but i change only over night and discharge during the day (excepting sunny days but now it is a winter and it is not too mamy sunny days). 
Today i have investigated the code and see that those values are calculated but not taken from inverter/bms/battery statistics.
So seems like there is a bug with those calculations.

### Reproduction Steps

Any charge shows wrongly calculated sensor data for:
- Battery SOH
- Today Life Cycles
- Total Life Cycles
For example, charging from 12% to 90% takes 3.37 lifecycles.

### Log

Not sure they are needed, if so - i will attach later.

### Version

24.12.22

### Home Assistant Core Version

2024.12.5

### Home Assistant Operating System Version

14.1

**Comment by davidrapan** [comment]
Did you set the nominal voltage in the configuration?

**Comment by iwannatalk** [comment]
> Did you set the nominal voltage in the configuration?

No, i thought it is taken from inverter data as this value is shown in stat.
Now i set in configuration 409 v.
Seems like it is more or less correct now. Showing 0.44 instead of 3.37 for today but not sure if it still correct.

**Comment by iwannatalk** [comment]
Btw, total battery cycles and soh is available in solarman stat.

**Comment by davidrapan** [comment]
What value you have in Device sensor?

**Comment by iwannatalk** [comment]
> What value you have in Device sensor?

![Screenshot_20241230_071200_Home Assistant](https://github.com/user-attachments/assets/83aaa89e-1d3d-4d27-924e-dcc354e0bdff)

But this value changes depending on the SOC.

**Comment by davidrapan** [comment]
Can you please show me what value you get when you read register number 224 using Developer tools >> ACTIONS >> Solarman: Read Holding Registers (Modbus Function Code 3)?

**Comment by iwannatalk** [comment]
> Can you please show me what value you get when you read register number 224 using Developer tools >> ACTIONS >> Solarman: Read Holding Registers (Modbus Function Code 3)?

![Screenshot_20241230_215924_Home Assistant](https://github.com/user-attachments/assets/79df2cce-1ce4-4a01-845e-9da564651c86)

**Comment by davidrapan** [comment]
What about 255, 10006 and 10048.

**Comment by iwannatalk** [comment]
> What about 255, 10006 and 10048.

0
100
30000

**Comment by davidrapan** [comment]
So it's proly at 100% at all times and thus not measured.
