### ISSUE TITLE
[Solved] Today‘s Losses entity with SG04LP3.yaml shows incorrect (high) value

### ISSUE THREAD

**Issue by PV-Joe** [davidrapan/ha-solarman#44]
Hi David,

are you or anyone else able to explain the value of „Today‘s Power Losses“ to me? I think this value is not calculated the right way maybe?

**My configuration:**
Deye 8K Hybrid SG04 LP3-EU

**Inverter_definition file: (unedited orriginal file from release v24.07.24):**
 deye_sg04lp3.yaml

**Result:**
![IMG_8399](https://github.com/user-attachments/assets/c9ecb464-9089-441f-b0a3-6545e5787a46)
(These values are from 0:00 until 8:00 o‘clock)

Thanx again for your help!
Joe

**Comment by davidrapan** [comment]
I guess it should be 0,4 right?

Here is mine:
![losses_example](https://github.com/user-attachments/assets/7ca3092b-94b8-49f4-b937-c9640966b359)

**Comment by PV-Joe** [comment]
Yes sure, here we go:

![IMG_5603](https://github.com/user-attachments/assets/bbb49d1a-4d35-463e-b2fd-250c1c4004f3)
![IMG_5604](https://github.com/user-attachments/assets/afeaf10c-0602-4e2f-b5e4-6508a54794e6)

**Comment by davidrapan** [comment]
Gosh If that would be right I would feel so sorry for u, lol!

Guess I'm gonna need Also the other values from the equation used...

My thoughts are that it's a scaling issue but if you used the same file (or copy pasted sensors even without changes) it's weird cause I'm using it too!

**Comment by davidrapan** [comment]
Ah! forget everything! I know where is the issue! You proly have a version where is a typo!

Try find in that definition file: "soperator"

HAHA!

**Comment by PV-Joe** [comment]
That was a quick fix 😄

I corrected the typo in:
deye_sg04lp3.yaml

From: soperator
To: operator

Result after fix:
![IMG_5605](https://github.com/user-attachments/assets/ef968b12-ecb0-4ded-9d8e-694bc436c528)

Well done David!
I think it will be fixed permanently with your next release right?

Keep going ☀️

**Comment by davidrapan** [comment]
Yes it's already committed and also as part of pre-releases I think. ;)

**Comment by davidrapan** [comment]
Leave this Issue open for some time for maybe other which could experience the same thing. ;)
