### ISSUE TITLE
Pre-release 24.07.29 causes issues when are not scheduled requests in every coordinator update loop

### ISSUE THREAD

**Issue by gedger** [davidrapan/ha-solarman#49]
Just tried the above and it raises a load of errors. Downgrading to .28 fixes.

Sorry, I've lost the log....

No I haven't, looking at it now it appears to have recovered just as I moved back to the previous version....I'll try again when I have some time just in case the inverter really was off-line?

[home-assistant_solarman_2024-07-30T08-21-37.172Z.log](https://github.com/user-attachments/files/16424682/home-assistant_solarman_2024-07-30T08-21-37.172Z.log)

**Comment by davidrapan** [comment]
As it's unfortunate this pre-release version is mainly for testing some niche cases of some users which are not able to run at all it proly will change multiple times before the release. But still thanks for the report for sure! I'm also running it but without any problems, maybe it's device dependent hm?

**Comment by gedger** [comment]
For info I've just tried the latest from main and it still causes issues so will need a tweak before releasing. Log attached which will hopefully help.

[home-assistant_solarman_2024-07-31T14-46-38.733Z.log](https://github.com/user-attachments/files/16443526/home-assistant_solarman_2024-07-31T14-46-38.733Z.log)

**Comment by davidrapan** [comment]
Not sure what exactly could cause that but I tried: [fix: Reverted partial request fulfillment](https://github.com/davidrapan/ha-solarman/commit/045986ba4f588716dd0c6fb9ba854b09f4bf65b8) as it turned out this feature is not necessary and original issue was caused by incorrect profile used.

**Comment by gedger** [comment]
Sorry, only just seen your Edit2: above. I have been seeing some really variable update intervals which I think has been also caused by the auto discovery. I have now disabled auto discovery which has improved matters plus have loaded 24.07.31 with no issues so far.

Going off-line

<img width="1152" alt="Screenshot 2024-08-01 at 09 57 47" src="https://github.com/user-attachments/assets/75f53038-c617-4197-9362-5299c5dfd384">

Coming on-line

<img width="1152" alt="Screenshot 2024-08-01 at 09 58 10" src="https://github.com/user-attachments/assets/8d285b00-53ff-4f48-a308-1ddfef378429">

I'm still struggling to debug what happened at 8.05am when I restarted HA with a slightly different profile that had 3 disabled parameters. Now I've disabled auto discovery and running the latest build I will evaluate again over the coming days.

**Comment by davidrapan** [comment]
Could you maybe do a test for me with 5 sec update interval for lets say a hour during the day? And also share the graph here?

**Comment by gedger** [comment]
Just realised, would you like a debug log too? If so I'll run again.

![IMG_0257](https://github.com/user-attachments/assets/c7bc674f-9341-4af3-8c1c-c76e40139134)

**Comment by davidrapan** [comment]
Thanks! And no it is not necessary I just wanted to see what are the usual update intervals on other installations.

Very appreciated!

**Comment by davidrapan** [comment]
What about the issues you were seeing? Are they still present in the last pre-release?

**Comment by gedger** [comment]
Latest release has been fine, I was just giving it a few days to confirm. I  couldn't determine the cause of the variable polling time when it varies between 30-40s as shown on the "coming on line" graph above.  Integration, inverter or network? If I ever find a way of provoking it then I'll raise an issue (if it is the integration) so I think it's safe to close this.
