### ISSUE TITLE
Discovery process too frequent 

### ISSUE THREAD

**Issue by gedger** [davidrapan/ha-solarman#51]
If the inverter cannot be reached the integration seems to go into a discovery loop of trying to find / connect to the inverter. This is too aggressive and appears to causes serious impact to the running of Home Assistant as the GUI becomes slow and unresponsive. The inverter also fails to come back on line as it is being bombarded with packets. Running a ping from another host the inverter does not respond but as soon as the integration is stopped then immediately starts responding to the ping and comes back on-line.

[home-assistant_solarman_using_non_custom_config.log](https://github.com/user-attachments/files/16452285/home-assistant_solarman_using_non_custom_config.log)

Using solis_1p8k-5g profile.

**Comment by davidrapan** [comment]
Discover happens only during the startup and at first directly to the saved IP and then when nothing responds on all interfaces. It really only depends on what Spook does to the integration.

**Comment by gedger** [comment]
Spook was not in the loop in this instance, plus I've looked through the code and it only calls the official API to disable polling in exactly the same as if you had done it from the HA GUI so shouldn't cause an issue......

I've now hopefully stopped HA using those interfaces, they are from my VPN and other docker containers so it has no need to scan those.

I still think there should be a significantly longer delay between the auto discovery, surely 20-30 seconds would be quick enough?

**Comment by davidrapan** [comment]
OMG that's a private range too. Never heard of that one lol.

**Comment by davidrapan** [comment]
I mean those are few packets anyway. The problem was the exception not the "size" of the discovery.

20-30 seconds is for HA eternity and will complain that whole initialization did not fit in 10 seconds range. 😆

**Comment by gedger** [comment]
I don't understand how/why it was slowing down HA so much and why my inverter stopped responding to pings but as soon as I stopped the integration then everything returned to normal, crazy. I've disabled discovery now so we'll see how it goes.

**Comment by davidrapan** [comment]
That discovery concise of UDP broadcast packets. That in any way can cripple the inverter...

**Comment by davidrapan** [comment]
Also, you said that Spook was not involved. But that discovery can kick in only when you restart the integration. As I said the discovery is only present at the start of integration.

**Comment by gedger** [comment]
Presumably that includes when you load a different inverter profile?

**Comment by davidrapan** [comment]
Changing the configuration does reload the integration.

**Comment by gedger** [comment]
Haven't had an issue since disabling discovery on my setup so we can close this.

**Comment by davidrapan** [comment]
I also adjusted the discovery flow to do it only once with 5 attempts and then one confirmation for the MAC if it succeeds.
