### ISSUE TITLE
Total Production is dropping to zero

### ISSUE THREAD

**Issue by switschel** [davidrapan/ha-solarman#65]
Since release v24.08.04 my microinverter total production value is shortly dropping to "0" and afterwards to the correct values. This leads to wrong statistics in the energy dashboard saying that the total production happend every day.

Would be great if the drop to zero on microinverter start can be avoided each day morning.

Since latest update dropping to zero
![image](https://github.com/user-attachments/assets/4dcc92d0-075b-4841-b6b3-16c09fd71dba)

Before the update you see that the value is just "not available"
![image](https://github.com/user-attachments/assets/44d51ea2-6fa6-4b4d-8cb9-16663a8aced8)

**Comment by davidrapan** [comment]
Ah, damn...

Would you be willing to test which beta version between versions 24.07.24 - 24.08.04 introduced this mess?

**Comment by davidrapan** [comment]
Yeah I guess you gonna have to do it manually then.

Even the latest commits as they are not part of any release yet.

**Comment by davidrapan** [comment]
Try 24.08.08

**Comment by switschel** [comment]
> Try 24.08.08 pre-release.

Tried it, same issue. Dropping to zero every day the microinverter starts.

**Comment by davidrapan** [comment]
What device are you using?

**Comment by switschel** [comment]
Deye sun600g3-eu with deye 2mppt profile

**Comment by davidrapan** [comment]
Your issue is proly cause by this: [fix: Deye microinverters validation lowered to 0.0](https://github.com/davidrapan/ha-solarman/commit/2a10012e5516655f3066aa1eb4e1fbdaa6625fa5)

it now somehow makes sense why it was there... But it caused issues with new inverters...

**Comment by davidrapan** [comment]
Try it with definition profile from this commit: [fix: Deye microinverters PV validation to 0.1](https://github.com/davidrapan/ha-solarman/commit/6ea759340755d80be6f96aadeaf39c509a3236e6)

**Comment by davidrapan** [comment]
Confirmed as fixed in: https://github.com/davidrapan/ha-solarman/issues/76
