### ISSUE TITLE
Settings Parameters

### ISSUE THREAD

**Issue by Mights001** [davidrapan/ha-solarman#9]
Hi, in the YAML File from this integreation are also Settings Parameters, but if i add the Inverter i get only the Sensor Entitys. 

![image](https://github.com/davidrapan/ha-solarman/assets/35522918/443d051a-5c73-4f4d-97a0-38a5a9e6e52b)

Is there any hidden option ?

**Comment by davidrapan** [comment]
Hi there, some of them are as an attributes attached to the Battery sensor. Click on the sensor, and at the bottom of the detail view click on attributes.

Have fun.

**Comment by Mights001** [comment]
Hi, so i did a lot of them with Esp Home and i love it the speed of your Integration. In any case i have time to can help you with the register let me now. 
![grafik](https://github.com/davidrapan/ha-solarman/assets/35522918/560f28f1-b6e4-41e1-b8cc-bd0cfcc8805b)
![grafik](https://github.com/davidrapan/ha-solarman/assets/35522918/a38cdc4e-8093-424f-84fa-699d44e4cc9c)

**Comment by davidrapan** [comment]
Hi, that would be really great! I'm currently working on implementing configuration of the inverter so anyone willing to test the functionality in the next release will be highly appreciated!

Thanks and have fun!

**Comment by Summer-of69** [comment]
Hi David!
Compliments for the great work. 👍I've been using your integration for about a week now. Works perfectly. Also, I use an ESP Home variant and can also configure the Deye with it. I look forward to this expansion in your solution!

**Comment by davidrapan** [comment]
Hi!

Thank you for your kind words! And sure, I will let you guys know in this issue tracker when there are any updates in this regard!

Thanks again and have fun!

**Comment by davidrapan** [comment]
Battery parameter settings were added in [feat: Battery parameters made configurable](https://github.com/davidrapan/ha-solarman/commit/6d3367d7260bfdb4f85a592d2afe596852b766fb)

**Comment by davidrapan** [comment]
Can please any of you guyes show me how are those sensors:
![combined](https://github.com/user-attachments/assets/31ea9a70-0807-49e3-96cb-d448886222af)

Presented in the device detail page? 😆 

Cheers!

**Comment by Mights001** [comment]
Hi, i just make this with Helpers and Nodered behind, in the detail View it looks so 
![grafik](https://github.com/user-attachments/assets/a6081f6d-49f0-42e6-aaa2-f41702f162ed)

And in Nodered i manipulate the Helpers 
![grafik](https://github.com/user-attachments/assets/c784d50f-60f1-4651-99b4-3b458abc2bc6)

**Comment by davidrapan** [comment]
Ou my, that's total jungle for me! 😆 But thanks!

Anyway when comes to an update of imlementing the controls within integration:
From Work Mode are left to do: Times and Grid/Gen charging.

General question:
That charging from grid and gen is made as an selectable enum on the inverter side. Is it a problem that it won't be a simple switch for both Grid/Gen separatedly?

**Comment by davidrapan** [comment]
All the necessary configurations is now possible using this integration (for SG04LP3 and SG01HP3).

But there is still plenty (not so crucial) to implement. So if let me know guys if forget any important ones.

And I have to say that working with the solarman HW is pain in the ass. I proly never saw something implemented so poorly... That being said setting of those configurables sometimes don't work very smoothly. I will try to improve on that in the future. 😉

**Comment by Mights001** [comment]
Hi, where can i find this controlls? I saw this in the yml from you but under Device i can see only the sensors.

**Comment by davidrapan** [comment]
You can't see the controls under device detail?

**Comment by Mights001** [comment]
No only the Sensors 
![grafik](https://github.com/user-attachments/assets/43af00cd-8be5-495d-be01-473cd7548f1c)

**Comment by davidrapan** [comment]
What device are you using?
![configuration](https://github.com/user-attachments/assets/dec7b5f5-628a-4e2a-9da1-c29932968ef1)

**Comment by davidrapan** [comment]
Ah you have to update to latest main. I can see that you are proly using latest realse version. You either have to update manually or wait cause another release is scheduled for today! 😉

**Comment by Mights001** [comment]
Hi, yes i made the update since 2 hours 

![grafik](https://github.com/user-attachments/assets/5f138302-a0a5-4b6e-9afe-8a39bbb99f7e)

I use the Battery Safety Controller and sometimes is a Alarm coming, we don't know at the moment what this is. But the System is working perfect :) 
https://github.com/shining-man/bsc_fw

**Comment by davidrapan** [comment]
I'm gonna release v24.07.24 today so wait a sec for that. (HACS only downloads latest release which is from a 10 days ago 😉 )

**Comment by Mights001** [comment]
Hi, is still the same i have only the Sensors
![grafik](https://github.com/user-attachments/assets/9630e3db-6777-4c8e-8ca2-bbcbb9fb7f36)

I try also to delet all and make it new, but nothing is changing

**Comment by davidrapan** [comment]
What device? What inverter profile?

**Comment by davidrapan** [comment]
If you are on the latest version and still don't see any new entities you are probably having different device than (SG04LP3 or SG01HP3) or using your custom inverter definitions profile.

**Comment by Mights001** [comment]
Sorry for the late reply i use your profile 
![grafik](https://github.com/user-attachments/assets/f17ad9c3-fff6-4810-b25b-cb5c64d364e6)

I also try to delet all Integration and Settings but i always get only the Sensors.

**Comment by davidrapan** [comment]
What version are you running?

**Comment by Mights001** [comment]
The latest one 
![grafik](https://github.com/user-attachments/assets/cac0de85-f83a-4d03-a213-384aa3a5abad)

**Comment by Mights001** [comment]
I think, there is something not delete from the old Solarman integration, because if i download the new one from you and i add a new device the always knows the parameters Dongel ID and IP Address, do you know where this is stored? i search in old the folders from HA but cant find it

**Comment by davidrapan** [comment]
First delete and re-add your device and use rather that original deye_sg04lp3 cause that custom one is now gone.

Then try to turn on that "Show beta versions" and then select the latest one a try download it...

Restart.

**Comment by davidrapan** [comment]
Hey @Mights001 were you successful?

**Comment by Mights001** [comment]
Hi, no i try all what i can do, but still the same thing only sensors are there

**Comment by davidrapan** [comment]
Did you update to the latest 24.08.04?

**Comment by Mights001** [comment]
yes but nothing change

**Comment by davidrapan** [comment]
What profile are you using? @Mights001 

Show me your HA, installed integration, your device, it's detail page, etc.

**Comment by davidrapan** [comment]
@Mights001 well.. let me know when you will time to look into it. :)

**Comment by Mights001** [comment]
Hi, I've been busy for a month and haven't had time for this. I just tried it again with the latest version and look, it works now. 
;-) 
THX

**Comment by davidrapan** [comment]
I'm glad to hear that! 😉
