### ISSUE TITLE
 The sensors do not update automatically

### ISSUE THREAD

**Issue by manuel833** [davidrapan/ha-solarman#91]
The sensors only update when the integration is reloaded.

![solarman_pv1](https://github.com/user-attachments/assets/710f0e45-f0e9-4322-9099-d2320489817c)

**Comment by davidrapan** [comment]
Hi @manuel833, didn't you accidentally turn of the polling?

**Anyway I will really need debug logs.**

**Comment by manuel833** [comment]
Where can I find polling?
[home-assistant_solarman_2024-08-17T17-03-14.083Z.log](https://github.com/user-attachments/files/16645722/home-assistant_solarman_2024-08-17T17-03-14.083Z.log)

**Comment by davidrapan** [comment]
When you click on the 3 dots next to the device and then under System options.

**Comment by manuel833** [comment]
sofar hyd 10ktl-3ph
sofar_g3hyd.yaml 

Solarman 24.08.16
Core: 2024.8.2
Supervisor: 2024.08.0
Operating System: 13.0

**Comment by davidrapan** [comment]
Hey @manuel833,

Open sofar_g3hyd.yaml profile file and on the 15 row you will find:
```
        class: ""
```
Change it to:
```
        class: "enum"
        options: ["waiting", "detection", "grid-connected", "emergency power supply", "recoverable fault", "permanent fault", "upgrade", "self-charging"]
```
**Notice the added row.**

And let me know if it helps. 😉

**Comment by davidrapan** [comment]
Oh I just noticed it also has:
```
        state_class: "measurement"
```
If you will still have issues change it to:
```
        state_class: ""
```

**Comment by manuel833** [comment]
The Solarman Inverter status is now working and the sensors are also functioning. Thank you.

**Comment by davidrapan** [comment]
[v24.08.17](https://github.com/davidrapan/ha-solarman/releases/tag/v24.08.17) also fixes the issue. 😉
